services:
  angular-frontend:
    build: .
    networks:
      - app-network
    expose:
      - 3000

  nginx-portfolio:
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx-portfolio.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist/dev_portfolio:/usr/share/nginx/html:ro # เพิ่มบรรทัดนี้
    networks:
      - app-network
    depends_on:
      - angular-frontend

networks:
  app-network:
    driver: bridge
